spring:
  application:
    name: front-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  shutdown: graceful

eureka:
  client:
    enabled: false

coupon:
  api:
    url: http://localhost:8081
