spring:
  application:
    name: front-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    hidden method:
      filter:
        enabled: true
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    enabled: false

server:
  port: 10384

# user-service
jwt:
  secret-key: secret

toss:
  payments:
    clientKey: secret

# Gateway
gateway:
  api:
    url: ""

# User
user:
  api:
    url: ""

# Order Payment
order:
  api:
    url: ""

# Book
book:
  api:
    url: ""

# Coupon
coupon:
  api:
    url: ""

#minio
minio:
  url: http://your-minio-url
  access-key: your-access-key
  secret-key: your-secret-key
  book-image-bucket: wannab-book-images
  review-image-bucket: wannab-review-images
  public-url: your-public-url

