spring:
  application:
    name: front-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    hidden method:
      filter:
        enabled: true
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

eureka:
  client:
    enabled: false

server:
  port: 10384

# user-service
jwt:
  secret-key: secret
