name: eureka server build and deploy

on:
  pull_request:
    branches:
      - release
      - main
    types:
      - closed

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
          if [ -f src/main/resources/application-local.yml ]; then
            mvn clean package \
              -Dspring.profiles.active=local \
              -Dspring.config.import=optional:classpath:/application-local.yml
          else
            mvn clean package
          fi

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image with Tag
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/wannab-front
          docker build -t $IMAGE:${{ github.sha }} .
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest

      - name: Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/wannab-front
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

      - name: Run Deployment Script
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: 8822
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export EUREKA_USERNAME=${{ secrets.EUREKA_USERNAME }}
            export EUREKA_PASSWORD=${{ secrets.EUREKA_PASSWORD }}
            
            bash /home/be10/be10-team5/script/front-deploy.sh front-service-v1 ${{ github.sha }} 10384 front-service-v2 10385
            bash /home/be10/be10-team5/script/front-deploy.sh front-service-v2 ${{ github.sha }} 10385 front-service-v1 10384
      
  notify-success:
    needs: build-and-deploy
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "botName": "wannab bot",
                 "text": "✅ 배포 성공!",
                 "attachments": [
                   {
                      "title" : "${{ github.repository }} 배포 성공",
                      "text" : "👤 머지한 사람: ${{ github.actor }}\n브랜치: ${{ github.base_ref }}",
                      "color" : "green"
                   }
                 ]
               }' \
               "${{ secrets.DOORAY_WEBHOOK_URL }}"

  notify-failure:
    needs: build-and-deploy
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Failure
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "botName": "wannab bot",
                 "text": "❌ 배포 실패...",
                 "attachments": [
                   {
                      "title" : "${{ github.repository }} 배포 실패",
                      "text" : "👤 머지한 사람: ${{ github.actor }}\n브랜치: ${{ github.base_ref }}",
                      "color" : "red"
                   }
                 ]
               }' \
               "${{ secrets.DOORAY_WEBHOOK_URL }}"
